services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: 
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://localhost:27017/challenge
    volumes:
      - ./api:/usr/src/app
    command: ["npm", "run", "dev"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"

volumes:
  mongo-data:
