services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork

  api:
    build: 
      context: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/challenge
    volumes:
      - ./api:/usr/src/app
    command: ["npm", "run", "dev"]
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npx", "nodemon", "-L", "--watch", "src", "--exec", "npm start"]
    networks:
      - mynetwork

volumes:
  mongo-data:
  
networks:
  mynetwork:
